defmodule NosnosTest do
  use ExUnit.Case
  doctest Nosnos

  describe "get_public_key/1" do
    test "derives correct public key from secret key" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      public_key = Nosnos.get_public_key(secret_key)

      expected_pubkey = Base.decode16!("132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d", case: :lower)

      assert public_key == expected_pubkey
      assert byte_size(public_key) == 32
    end
  end

  describe "sign/2 and verify/3" do
    test "signs and verifies a message correctly" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      public_key = Nosnos.get_public_key(secret_key)

      msg = :crypto.hash(:sha256, "test message")
      signature = Nosnos.sign(secret_key, msg)

      assert byte_size(signature) == 64
      assert Nosnos.verify(public_key, msg, signature) == true
    end

    test "verification fails with wrong message" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      public_key = Nosnos.get_public_key(secret_key)

      msg1 = :crypto.hash(:sha256, "message 1")
      msg2 = :crypto.hash(:sha256, "message 2")

      signature = Nosnos.sign(secret_key, msg1)

      assert Nosnos.verify(public_key, msg2, signature) == false
    end

    test "verification fails with wrong public key" do
      secret_key1 = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      secret_key2 = :crypto.strong_rand_bytes(32)

      public_key2 = Nosnos.get_public_key(secret_key2)

      msg = :crypto.hash(:sha256, "test message")
      signature = Nosnos.sign(secret_key1, msg)

      assert Nosnos.verify(public_key2, msg, signature) == false
    end
  end

  describe "calculate_event_id/5" do
    test "calculates event ID consistently" do
      pubkey = "132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d"
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = "test"

      event_id1 = Nosnos.calculate_event_id(pubkey, created_at, kind, tags, content)
      event_id2 = Nosnos.calculate_event_id(pubkey, created_at, kind, tags, content)

      assert event_id1 == event_id2
      assert byte_size(event_id1) == 32
    end
  end

  describe "sign_event/5" do
    test "creates a valid signed event" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = "test event"

      event = Nosnos.sign_event(secret_key, created_at, kind, tags, content)

      assert is_map(event)
      assert Map.has_key?(event, :id)
      assert Map.has_key?(event, :pubkey)
      assert Map.has_key?(event, :created_at)
      assert Map.has_key?(event, :kind)
      assert Map.has_key?(event, :tags)
      assert Map.has_key?(event, :content)
      assert Map.has_key?(event, :sig)

      assert String.length(event.id) == 64
      assert String.length(event.pubkey) == 64
      assert String.length(event.sig) == 128
      assert event.created_at == created_at
      assert event.kind == kind
      assert event.content == content

      # Verify the event is valid
      assert Nosnos.verify_event(event.id, event.pubkey, event.created_at, event.kind, event.tags, event.content, event.sig) == true
    end

    test "signs event with tags" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      created_at = 1700000000
      kind = 1
      tags = ~s([["e","event_id_here"],["p","pubkey_here"]])
      content = "reply message"

      event = Nosnos.sign_event(secret_key, created_at, kind, tags, content)

      assert Nosnos.verify_event(event.id, event.pubkey, event.created_at, event.kind, event.tags, event.content, event.sig) == true
    end

    test "handles special characters in content" do
      secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = ~s(Hello "World"\nWith newlines\tand tabs\\and backslashes)

      event = Nosnos.sign_event(secret_key, created_at, kind, tags, content)

      assert event.content == content
      assert Nosnos.verify_event(event.id, event.pubkey, event.created_at, event.kind, event.tags, event.content, event.sig) == true
    end
  end

  describe "verify_event/7" do
    test "verifies real Nostr event generated by nak" do
      # Generated with: nak event -c "Hello from nak!" --sec 037ed39e07fec9741b4133e3560a5188a1b6eda007817e319c79a5f425530280 --created-at 1700000000
      id = "356faddbfae35f27be9ae9480a6da1134c26a438e7ef4d360873ce4d6583a4d5"
      pubkey = "132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d"
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = "Hello from nak!"
      sig = "fb8f88a9dbefbace8285b81c71773953587c6519a9d1c30154a074abba6a4ab25be97012849b5dbf57f90f4c93eddc7e5b6a22d7d2ec8a11ec249a5643474e61"

      assert Nosnos.verify_event(id, pubkey, created_at, kind, tags, content, sig) == true
    end

    test "rejects event with invalid signature" do
      id = "356faddbfae35f27be9ae9480a6da1134c26a438e7ef4d360873ce4d6583a4d5"
      pubkey = "132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d"
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = "Hello from nak!"
      sig = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

      assert Nosnos.verify_event(id, pubkey, created_at, kind, tags, content, sig) == false
    end

    test "rejects event with mismatched ID" do
      id = "0000000000000000000000000000000000000000000000000000000000000000"
      pubkey = "132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d"
      created_at = 1700000000
      kind = 1
      tags = "[]"
      content = "Hello from nak!"
      sig = "fb8f88a9dbefbace8285b81c71773953587c6519a9d1c30154a074abba6a4ab25be97012849b5dbf57f90f4c93eddc7e5b6a22d7d2ec8a11ec249a5643474e61"

      assert Nosnos.verify_event(id, pubkey, created_at, kind, tags, content, sig) == false
    end
  end

  describe "type marshalling" do
    test "handles binary keys correctly" do
      secret_key = :crypto.strong_rand_bytes(32)
      public_key = Nosnos.get_public_key(secret_key)

      assert is_binary(public_key)
      assert byte_size(public_key) == 32
    end

    test "validates signature is binary" do
      secret_key = :crypto.strong_rand_bytes(32)
      msg = :crypto.hash(:sha256, "test")
      signature = Nosnos.sign(secret_key, msg)

      assert is_binary(signature)
      assert byte_size(signature) == 64
    end
  end
end
