#!/usr/bin/env elixir

# Demo script showing Nosnos Zigler wrapper functionality

IO.puts("=== Nosnos Zigler Wrapper Demo ===\n")

# Generate a test secret key (DO NOT use this in production!)
secret_key = Base.decode16!("037ED39E07FEC9741B4133E3560A5188A1B6EDA007817E319C79A5F425530280", case: :mixed)

IO.puts("1. Deriving public key from secret key...")
public_key = Nosnos.get_public_key(secret_key)
IO.puts("   Public key: #{Base.encode16(public_key, case: :lower)}\n")

IO.puts("2. Signing a message with BIP-340 Schnorr...")
msg = :crypto.hash(:sha256, "Hello from Nosnos!")
signature = Nosnos.sign(secret_key, msg)
IO.puts("   Message: \"Hello from Nosnos!\"")
IO.puts("   Signature: #{Base.encode16(signature, case: :lower)}\n")

IO.puts("3. Verifying the signature...")
is_valid = Nosnos.verify(public_key, msg, signature)
IO.puts("   Verification result: #{is_valid}\n")

IO.puts("4. Creating and signing a Nostr event...")
timestamp = System.system_time(:second)
tags = "[]"
content = "Hello Nostr from Zig + Elixir!"

event = Nosnos.sign_event(secret_key, timestamp, 1, tags, content)
IO.puts("   Event ID: #{event.id}")
IO.puts("   Pubkey: #{event.pubkey}")
IO.puts("   Created at: #{event.created_at}")
IO.puts("   Kind: #{event.kind}")
IO.puts("   Content: #{event.content}")
IO.puts("   Signature: #{event.sig}\n")

IO.puts("5. Verifying the Nostr event...")
event_valid = Nosnos.verify_event(event)
IO.puts("   Event verification: #{event_valid}\n")

IO.puts("6. Verifying a real Nostr event generated by nak...")
# Generated with: nak event -c "Hello from nak!" --sec 037ed39e07fec9741b4133e3560a5188a1b6eda007817e319c79a5f425530280 --created-at 1700000000
real_event = %{
  id: "356faddbfae35f27be9ae9480a6da1134c26a438e7ef4d360873ce4d6583a4d5",
  pubkey: "132fc0db6c5946dabd675914603840bf3042e5b6d1cd1865be73c9cf8fd38e8d",
  created_at: 1700000000,
  kind: 1,
  tags: "[]",
  content: "Hello from nak!",
  sig: "fb8f88a9dbefbace8285b81c71773953587c6519a9d1c30154a074abba6a4ab25be97012849b5dbf57f90f4c93eddc7e5b6a22d7d2ec8a11ec249a5643474e61"
}

real_event_valid = Nosnos.verify_event(real_event)
IO.puts("   Real event verification: #{real_event_valid}")
IO.puts("   Content: #{real_event.content}\n")

IO.puts("=== Demo Complete ===")
IO.puts("All Zig functions are successfully callable from Elixir via Zigler!")
